---
title: Load and visualize data from a variety of sources
---

We demonstrate here how to load data from a variety of data sources and visualize them using [`SpacePhysicsMakie.jl`](https://juliaspacephysics.github.io/SpacePhysicsMakie.jl/).

```{julia}
#| code-summary: Setup
dir = "tutorials/data_loading"
if isdir(dir)
    cd(dir)
end

Pkg.activate(".")
Pkg.resolve()
Pkg.instantiate()

using CairoMakie, SpacePhysicsMakie
```

## Get data with `CDAWeb`

[CDAWeb.jl](https://github.com/JuliaSpacePhysics/CDAWeb.jl) provides direct access to NASA's CDAWeb RESTful services with local caching and fine-grained control over data retrieval.

It could be installed at REPL via `using Pkg; Pkg.add("CDAWeb")`.

```{julia}
import CDAWeb
t0 = "2024-01-02"
t1 = "2024-01-03"
# Fetch ACE magnetic field data
data1 = CDAWeb.get_data("AC_H0_SWE", "V_GSE", t0, t1)
```

### Plot the data

```{julia}
tplot(data1, add_title=true)
```

## Get data with `Speasy`

[Speasy.jl](https://github.com/SciQLop/Speasy.jl) provides functions to load data from main Space Physics WebServices (CDA,SSC,AMDA,..).

It could be installed at REPL via `using Pkg; Pkg.add("Speasy")`.

```{julia}
import Speasy

data2 = Speasy.get_data("cda/OMNI_HRO_1MIN/Pressure", t0, t1; sanitize=true)
```

### Plot the data

```{julia}
tplot(data2)
```

## Get data using Heliophysics Application Programmer's Interface (HAPI)

[HAPIClient.jl](https://github.com/JuliaSpacePhysics/HAPIClient.jl) provides functions to load data from HAPI-compliant servers.

It could be installed at REPL via `using Pkg; Pkg.add("HAPIClient")`.

```{julia}
import HAPIClient

vars = HAPIClient.get_data("CDAWeb/AC_H0_MFI/Magnitude,BGSEc", t0, t1)
```

### Plot the data

```{julia}
tplot(vars)
```

## Get data with `PySPEDAS`

[PySPEDAS.jl](https://github.com/JuliaSpacePhysics/PySPEDAS.jl) provides a Julia interface to the [PySPEDAS](https://github.com/spedas/pyspedas) Python package, offering a similar API for Julia users to utilize the existing Python routines.

It could be installed at REPL via `using Pkg; Pkg.add("PySPEDAS")`.

```{julia}
using PySPEDAS.Projects

# Same as more verbose `pyspedas.projects.themis.fgm(...)`
tvars = themis.fgm([t0, t1], time_clip=true, probe="d");
```

### Plot the data

```{julia}
tplot((tvars.thd_fgs_gsm, tvars.thd_fgs_btotal))
```

## Composite plot

Combine all the data into a single plot with multiple panels.

```{julia}
tplot((data1, data2, vars..., tvars.thd_fgs_gsm), add_title=true)
```

## Reproducibility

::: {.callout-note collapse="true"}
## This tutorial was built using these direct dependencies

```{julia}
using Pkg
Pkg.status()
```
:::

::: {.callout-note collapse="true"}
## Machine and Julia version information

```{julia}
using InteractiveUtils # hide
versioninfo()
```
:::